"""
HTML report generator for MAS-Sentry audit results.
Produces a self-contained single-file HTML report.
"""
from .report_model import MASAuditReport

SEVERITY_COLORS = {
    "CRITICAL": "#e74c3c",
    "HIGH":     "#e67e22",
    "MEDIUM":   "#f1c40f",
    "LOW":      "#2ecc71",
    "INFO":     "#3498db",
}

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>MAS-Sentry Report — {session_id}</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: 'Segoe UI', sans-serif; background: #0d1117; color: #c9d1d9; }}
  header {{ background: #161b22; border-bottom: 2px solid #e74c3c;
            padding: 20px 40px; display: flex; align-items: center; gap: 20px; }}
  header h1 {{ color: #e74c3c; font-size: 1.6rem; }}
  header p  {{ color: #8b949e; font-size: 0.85rem; margin-top: 4px; }}
  .container {{ max-width: 1100px; margin: 30px auto; padding: 0 20px; }}
  .stats-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(160px,1fr));
                 gap: 16px; margin-bottom: 30px; }}
  .stat-card {{ background: #161b22; border: 1px solid #30363d;
                border-radius: 8px; padding: 20px; text-align: center; }}
  .stat-card .value {{ font-size: 2rem; font-weight: bold; color: #58a6ff; }}
  .stat-card .label {{ font-size: 0.8rem; color: #8b949e; margin-top: 4px; }}
  .section {{ margin-bottom: 30px; }}
  .section h2 {{ color: #58a6ff; border-bottom: 1px solid #30363d;
                  padding-bottom: 8px; margin-bottom: 16px; font-size: 1.1rem; }}
  table {{ width: 100%; border-collapse: collapse; font-size: 0.88rem; }}
  th {{ background: #21262d; color: #8b949e; padding: 10px 12px;
        text-align: left; border-bottom: 1px solid #30363d; }}
  td {{ padding: 10px 12px; border-bottom: 1px solid #21262d; vertical-align: top; }}
  tr:hover td {{ background: #161b22; }}
  .badge {{ display: inline-block; padding: 2px 8px; border-radius: 4px;
             font-size: 0.75rem; font-weight: bold; color: #0d1117; }}
  .meta-box {{ background: #161b22; border: 1px solid #30363d;
               border-radius: 8px; padding: 16px; font-size: 0.85rem;
               display: grid; grid-template-columns: 1fr 1fr; gap: 8px; }}
  .meta-box span {{ color: #8b949e; }}
  footer {{ text-align: center; padding: 30px; color: #484f58; font-size: 0.8rem; }}
</style>
</head>
<body>
<header>
  <div>
    <h1>🛡️ MAS-Sentry-Toolkit</h1>
    <p>Multi-Agent System Security Audit Report</p>
  </div>
</header>
<div class="container">

  <!-- Meta -->
  <div class="section">
    <h2>Scan Information</h2>
    <div class="meta-box">
      <div><span>Session ID:</span> {session_id}</div>
      <div><span>Target:</span> {target}</div>
      <div><span>Protocol:</span> {protocol}</div>
      <div><span>Generated:</span> {generated_at}</div>
      <div><span>Toolkit:</span> MAS-Sentry v{version}</div>
    </div>
  </div>

  <!-- Statistics -->
  <div class="section">
    <h2>Executive Summary</h2>
    <div class="stats-grid">
      <div class="stat-card">
        <div class="value" style="color:#e74c3c">{crit}</div>
        <div class="label">CRITICAL</div>
      </div>
      <div class="stat-card">
        <div class="value" style="color:#e67e22">{high}</div>
        <div class="label">HIGH</div>
      </div>
      <div class="stat-card">
        <div class="value" style="color:#f1c40f">{med}</div>
        <div class="label">MEDIUM</div>
      </div>
      <div class="stat-card">
        <div class="value" style="color:#2ecc71">{low}</div>
        <div class="label">LOW</div>
      </div>
      <div class="stat-card">
        <div class="value">{agents}</div>
        <div class="label">Agents Analyzed</div>
      </div>
      <div class="stat-card">
        <div class="value" style="color:#e74c3c">{rogue}</div>
        <div class="label">Rogue Agents</div>
      </div>
      <div class="stat-card">
        <div class="value" style="color:#e67e22">{max_score}</div>
        <div class="label">Max Anomaly Score</div>
      </div>
      <div class="stat-card">
        <div class="value">{stride}</div>
        <div class="label">STRIDE Threats</div>
      </div>
    </div>
  </div>

  <!-- Protocol Findings -->
  <div class="section">
    <h2>Protocol Vulnerability Findings</h2>
    {findings_table}
  </div>

  <!-- ABFP -->
  <div class="section">
    <h2>ABFP Agent Behavioral Fingerprints</h2>
    {abfp_table}
  </div>

  <!-- STRIDE -->
  <div class="section">
    <h2>STRIDE Threat Mapping</h2>
    {stride_table}
  </div>

</div>
<footer>
  Generated by MAS-Sentry-Toolkit v{version} |
  ABFP — Agent Behavioral Fingerprinting Protocol |
  For authorized security testing only
</footer>
</body>
</html>"""


class HTMLReportGenerator:

    def __init__(self, report: MASAuditReport):
        self.report = report

    def _badge(self, severity: str) -> str:
        color = SEVERITY_COLORS.get(severity, "#888")
        return f'<span class="badge" style="background:{color}">{severity}</span>'

    def _findings_table(self) -> str:
        if not self.report.protocol_findings:
            return "<p style='color:#8b949e'>No protocol findings recorded.</p>"
        rows = ""
        for f in sorted(self.report.protocol_findings,
                        key=lambda x: ["CRITICAL","HIGH","MEDIUM","LOW"].index(
                            x.severity) if x.severity in
                            ["CRITICAL","HIGH","MEDIUM","LOW"] else 99):
            rows += (
                f"<tr><td>{self._badge(f.severity)}</td>"
                f"<td><strong>{f.title}</strong><br>"
                f"<small style='color:#8b949e'>{f.description}</small></td>"
                f"<td style='color:#58a6ff'>{f.remediation}</td></tr>"
            )
        return (
            "<table><thead><tr>"
            "<th>Severity</th><th>Finding</th><th>Remediation</th>"
            "</tr></thead><tbody>" + rows + "</tbody></table>"
        )

    def _abfp_table(self) -> str:
        if not self.report.abfp_fingerprints:
            return "<p style='color:#8b949e'>No ABFP data collected.</p>"
        rows = ""
        for fp in sorted(self.report.abfp_fingerprints,
                         key=lambda x: x.get("anomaly_score", 0),
                         reverse=True):
            score = fp.get("anomaly_score", 0)
            color = ("#e74c3c" if score >= 70 else
                     "#e67e22" if score >= 40 else
                     "#f1c40f" if score >= 20 else "#2ecc71")
            flags = ", ".join(fp.get("threat_flags", [])) or "—"
            rows += (
                f"<tr>"
                f"<td style='color:#58a6ff'>{fp.get('agent_id','?')}</td>"
                f"<td>{fp.get('message_count',0)}</td>"
                f"<td style='color:{color};font-weight:bold'>{score:.1f}/100</td>"
                f"<td>{fp.get('timing',{}).get('mean_interval_ms',0):.0f} ms</td>"
                f"<td>{fp.get('payload',{}).get('encoding','?')}</td>"
                f"<td style='color:#e74c3c'>{flags}</td>"
                f"</tr>"
            )
        return (
            "<table><thead><tr>"
            "<th>Agent ID</th><th>Messages</th><th>Anomaly Score</th>"
            "<th>Interval</th><th>Encoding</th><th>Threat Flags</th>"
            "</tr></thead><tbody>" + rows + "</tbody></table>"
        )

    def _stride_table(self) -> str:
        if not self.report.stride_threats:
            return "<p style='color:#8b949e'>No STRIDE threats mapped.</p>"
        rows = ""
        for t in sorted(self.report.stride_threats,
                        key=lambda x: x.get("cvss_score", 0),
                        reverse=True):
            rows += (
                f"<tr>"
                f"<td style='color:#8b949e'>{t.get('threat_id','?')}</td>"
                f"<td>{self._badge(t.get('severity','?'))}</td>"
                f"<td>{t.get('category','?')}</td>"
                f"<td><strong>{t.get('title','?')}</strong></td>"
                f"<td style='color:#e74c3c'>{t.get('cvss_score','?')}</td>"
                f"<td>{t.get('mitigation','?')}</td>"
                f"</tr>"
            )
        return (
            "<table><thead><tr>"
            "<th>ID</th><th>Severity</th><th>Category</th>"
            "<th>Title</th><th>CVSS</th><th>Mitigation</th>"
            "</tr></thead><tbody>" + rows + "</tbody></table>"
        )

    def generate(self) -> str:
        self.report.compute_statistics()
        s = self.report.statistics
        sev = s.get("severity_breakdown", {})
        return HTML_TEMPLATE.format(
            session_id=self.report.meta.session_id,
            target=self.report.meta.target,
            protocol=self.report.meta.protocol,
            generated_at=self.report.meta.generated_at,
            version=self.report.meta.toolkit_version,
            crit=sev.get("CRITICAL", 0),
            high=sev.get("HIGH", 0),
            med=sev.get("MEDIUM", 0),
            low=sev.get("LOW", 0),
            agents=s.get("agents_analyzed", 0),
            rogue=s.get("rogue_agents", 0),
            max_score=s.get("max_anomaly_score", 0),
            stride=s.get("stride_threats_mapped", 0),
            findings_table=self._findings_table(),
            abfp_table=self._abfp_table(),
            stride_table=self._stride_table(),
        )

    def save(self, path: str):
        html = self.generate()
        with open(path, "w", encoding="utf-8") as f:
            f.write(html)
        print(f"[+] HTML report saved: {path}")
