# SPDX-License-Identifier: AGPL-3.0-or-later
"""Markdown report generator for MAS-Sentry audit results."""

from .report_model import MASAuditReport


class MarkdownReportGenerator:
    def __init__(self, report: MASAuditReport):
        self.report = report

    def generate(self) -> str:
        report = self.report
        report.compute_statistics()
        s = report.statistics
        sev = s.get("severity_breakdown", {})
        lines = [
            "# MAS-Sentry Audit Report",
            f"**Session:** {report.meta.session_id}  ",
            f"**Target:** {report.meta.target}  ",
            f"**Protocol:** {report.meta.protocol}  ",
            f"**Generated:** {report.meta.generated_at}  ",
            "",
            "## Executive Summary",
            "| Severity | Count |",
            "|----------|-------|",
            f"| CRITICAL | {sev.get('CRITICAL', 0)} |",
            f"| HIGH     | {sev.get('HIGH', 0)} |",
            f"| MEDIUM   | {sev.get('MEDIUM', 0)} |",
            f"| LOW      | {sev.get('LOW', 0)} |",
            f"| Agents   | {s.get('agents_analyzed', 0)} |",
            f"| Rogue    | {s.get('rogue_agents', 0)} |",
            "",
            "## Protocol Findings",
        ]
        if not report.protocol_findings:
            lines.append("_No findings recorded._")
        else:
            lines.append("| Severity | Title | Remediation |")
            lines.append("|----------|-------|-------------|")
            for f in report.protocol_findings:
                lines.append(f"| {f.severity} | {f.title} | {f.remediation} |")
        lines += ["", "## ABFP Fingerprints"]
        if not report.abfp_fingerprints:
            lines.append("_No ABFP data._")
        else:
            lines.append("| Agent | Messages | Score | Flags |")
            lines.append("|-------|----------|-------|-------|")
            for fp in report.abfp_fingerprints:
                flags = ", ".join(fp.get("threat_flags", [])) or "—"
                lines.append(
                    f"| {fp.get('agent_id', '?')} "
                    f"| {fp.get('message_count', 0)} "
                    f"| {fp.get('anomaly_score', 0):.1f} "
                    f"| {flags} |"
                )
        lines += ["", "## STRIDE Threats"]
        if not report.stride_threats:
            lines.append("_No threats mapped._")
        else:
            lines.append("| ID | Severity | Category | CVSS |")
            lines.append("|----|----------|----------|------|")
            for t in report.stride_threats:
                lines.append(
                    f"| {t.get('threat_id', '?')} "
                    f"| {t.get('severity', '?')} "
                    f"| {t.get('category', '?')} "
                    f"| {t.get('cvss_score', '?')} |"
                )
        lines += ["", "---", "_Generated by MAS-Sentry-Toolkit v0.1.0_"]
        return "\n".join(lines)

    def save(self, path: str):
        with open(path, "w") as f:
            f.write(self.generate())
        print(f"[+] Markdown report saved: {path}")
