# SPDX-License-Identifier: AGPL-3.0-or-later
"""MCP audit HTML report renderer."""

from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from jinja2 import Template

# autoescape=True: `detail` and `target` come from adversarial sources
# (MCP server responses, user-supplied URIs). Without escaping a poisoned tool
# description containing <script> would be rendered as live HTML in the report.
_TEMPLATE = Template(
    """<!doctype html>
<html lang="en"><head><meta charset="utf-8"><title>MCP Scan — {{ target }}</title>
<style>
body{font-family:system-ui;background:#0f172a;color:#e2e8f0;padding:2rem;max-width:1100px;margin:auto}
h1{border-bottom:2px solid #334155;padding-bottom:.5rem}
.f{background:#1e293b;padding:1rem;margin:.6rem 0;border-radius:4px;border-left:4px solid #64748b}
.sev-CRITICAL{border-left-color:#ef4444}.sev-HIGH{border-left-color:#f97316}
.sev-MEDIUM{border-left-color:#eab308}.sev-INFO{border-left-color:#3b82f6}
.cve{display:inline-block;background:#7f1d1d;color:#fee;padding:.1rem .4rem;border-radius:3px;margin-right:.4rem}
code{background:#0b1220;padding:.1rem .3rem;border-radius:3px}
</style></head><body>
<h1>MCP Audit Report</h1>
<p><b>Target:</b> <code>{{ target }}</code> · <b>Generated:</b> {{ generated_at }}</p>
<p><b>Findings:</b> {{ findings|length }}</p>
{% for f in findings %}
<div class="f sev-{{ f.severity }}">
  <strong>[{{ f.severity }}] {{ f.check }}</strong>
  <p>{{ f.detail }}</p>
</div>
{% endfor %}
<hr><p style="color:#64748b">
  Generated by mas-sentry-toolkit · CVE refs: vulnerablemcp.info · OWASP Agentic Top 10 (2026)
</p>
</body></html>""",
    autoescape=True,
)


def render_mcp_html(target: str, findings: list[dict[str, Any]], out_path: Path) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(
        _TEMPLATE.render(
            target=target,
            findings=findings,
            generated_at=datetime.now(UTC).isoformat(timespec="seconds"),
        )
    )
